# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt
#
# ReadTheDocs configuration.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

# Build all the formats
formats:
  - epub
  - htmlzip
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
  system_packages: false